name: build-container
on: [push]

env:
  REGISTRY: ghcr.io/${{ github.repository }}
  IMAGE_NAME: crescent_base

jobs:
  build_container:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]  # add arm64 for Raspberry Pi 5
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Derive platform tag
        id: vars
        shell: bash
        run: |
          set -euo pipefail
          # e.g. linux/amd64 -> amd64, linux/arm64 -> arm64
          SHORT="${{ matrix.platform }}"
          SHORT="${SHORT#linux/}"
          echo "short=${SHORT}" >> "$GITHUB_OUTPUT"
          echo "Building for platform: ${{ matrix.platform }} (tag suffix: ${SHORT})"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (per-platform tags)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          provenance: false
          sbom: false
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ steps.vars.outputs.short }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short }}
